version: "3.8"

services:
  teamspeakclaw:
    image: ghcr.io/dr1mh4x/teamspeakclaw:latest # 或使用 ghcr.nju.edu.cn
    container_name: teamspeakclaw
    user: "1000:10" #PUID:GUID
    restart: unless-stopped
    volumes:
      # 配置文件目录（必须）
      - ./config:/app/config
      # 日志目录
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    networks:
      - openteamspeak

networks:
  openteamspeak:
    driver: bridge
