version: "3.8"

services:
  teamspeakclaw:
    image: ghcr.io/dr1mh4x/teamspeakclaw:latest
    container_name: teamspeakclaw
    user: "1000:10" #PUID:GUID
    restart: unless-stopped
    volumes:
      # 配置文件目录（必须）
      - ./config:/app/config
      # 日志目录
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    networks:
      - openteamspeak
    depends_on:
      - stt-api

  stt-api:
    image: ghcr.io/dr1mh4x/moonshinev2-stt:latest
    container_name: sherpa-stt-api
    restart: unless-stopped
    volumes:
      # STT 模型目录（只读）
      - ./models:/models:ro
    environment:
        MODEL_PATH: /models
        MODEL_NAME: moonshinev2
        NUM_THREADS: "4"
    networks:
      - openteamspeak

networks:
  openteamspeak:
    driver: bridge